export const SAVE_BASIC_INFO = 'SAVE_BASIC_INFO'
export const SAVE_SECTION_INFO = 'SAVE_SECTION_INFO'
export const ADD_DYNAMIC_FIELD = 'ADD_DYNAMIC_FIELD'
export const UPDATE_FIELD_VALUES = 'UPDATE_FIELD_VALUES'
